### ISSUE TITLE
does not write win.txt file

### ISSUE THREAD

**Issue by Netlakes** [mobb111/mfbc-master#1]
I inserted some addresses for testing, I created a file with the passwords of the addresses I made, but it does not write to the file win.txt
that is, this script does not work.

**Comment by granula** [comment]
10 min work and 


Traceback (most recent call last):
  File "mfbc.py", line 184, in <module>
    with file as f:
ValueError: I/O operation on closed file.

**Comment by mobb111** [comment]
granula now it's working u can check out some new function i added

**Comment by mobb111** [comment]
Netlakes what are u talking about if u need to check if add is in file u need to modife script but i test it and
when addres is generated and if add is in file will find it if u want to know more how i tested it i can give u script code

**Comment by granula** [comment]
No working
15 min and   https://pix.my/TGKBkN
menu 5
paspshare 3

**Comment by granula** [comment]
Why put the script without checking it?

**Comment by enzohack2** [comment]
the script i'm using on termux in android and it works. the only thing does not store the scanned wallets? if so where?

**Comment by mobb111** [comment]
ok u want all to save? if all to save need to rewrite script

V V sob., 22. jun. 2019 ob 17:19 je oseba enzohack2 <
notifications@github.com> napisala:

**Comment by gadroic** [comment]
Hello pls write script to save mnemonics,wif, addresses in a text file.

**Comment by mobb111** [comment]
i will send u tomorrow

V V sre., 17. jul. 2019 ob 19:50 je oseba gadroic <notifications@github.com>
napisala:
