### ISSUE TITLE
The script does not work.

### ISSUE THREAD

**Issue by granula** [mobb111/mfbc-master#2]
https://pix.my/xnAhVK

menu 5,6,7,8 working 15min and stoping.
https://pix.my/TGKBkN

**Comment by adrijan111** [comment]
yes when file is readed and come to end u need to insert it again, find bigger dict file and wil be working

**Comment by mobb111** [comment]
yes becose the file come to end

**Comment by mobb111** [comment]
loook sec pic

**Comment by granula** [comment]
Just do some nonsense.

I put 5 words from the dictionary in 2000 words. Variants of busting for 100 years would be enough, and ended in 15 minutes.

You did line by line. This is nonsense.

Then make it line by line, but so that the line reads not one word, but the whole sentence.

Now in this program in the menu 5,6,7.8 meaning zero.

**Comment by mobb111** [comment]
granula now its updated try it now i tested it for week and all working fine try it and tell me if it' ok
