### ISSUE TITLE
hmac issues

### ISSUE THREAD

**Issue by WesNz** [mobb111/mfbc-master#3]
H 

playing around with your script but seem to be having some issues or not understanding.

--------------------------------------------
**COMMAND : sudo python3 mfbc.py**

Choose your number: 8
Menu 8 has been selected

Enter name or path of txt file: BIP0039.txt
Enter number mnemonic code words: 12
Traceback (most recent call last):
  File "mfbc.py", line 486, in <module>
    exponent = base64.b64encode(hmac.new(secret, message, digestmod=hashlib.sha512).digest())
NameError: name 'hmac' is not defined
abe@ABE:~/Desktop/mfbc-master$ hashlib
hashlib: command not found
abe@ABE:~/Desktop/mfbc-master$ pip install --user hashlib
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: hashlib in /usr/local/lib/python2.7/dist-packages/hashlib-20081119-py2.7-linux-x86_64.egg (20081119)
abe@ABE:~/Desktop/mfbc-master$

---------------------------------------------

**Comment by mobb111** [comment]
did u read description? python3+ in my case tested on kali linux and windows python 3.7 working fine
